version: '3.9'

services:
  certbot:
      image: ${CERTBOT_IMAGE_NAME:-certtest:new}
      volumes:
        - ssl_certs_testing:/etc/letsencrypt
      environment:
        CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN}
        LE_NOTIFY_EMAIL: ${LE_NOTIFY_EMAIL}
        CLOUDFLARE_DOMAIN_LIST: ${CLOUDFLARE_DOMAIN_LIST}
      # Uncomment to enter/troubleshoot
      # entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]

volumes:
  ssl_certs_testing: