version: '3.9'

services:
  certbot:
      image: snk-certbot:1.0
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
        - ssl_certs:/etc/letsencrypt
      environment:
        CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN}
        CLOUDFLARE_EMAIL: ${CLOUDFLARE_EMAIL}
        CLOUDFLARE_DOMAIN_LIST: ${CLOUDFLARE_DOMAIN_LIST}

volumes:
  ssl_certs: